# Dockerfile used for building
FROM ubuntu:latest
RUN apt-get update && apt-get install -y \
	wget \
	git \
	gcc \
    nano

RUN wget https://dl.google.com/go/go1.14.1.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.14.1.linux-amd64.tar.gz
ENV PATH="/usr/local/go/bin:${PATH}"
ENV PATH="${PATH}:/root/go/bin"

