name: Build and release

on:
  push:
    branches: [master, develop, branches/cidi]
  pull_request:
    branches: [master, develop, branches/cidi]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.19.2"

      - name: Build & Test
        run: |
          echo Building ...
          ./build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: vxxx
          release_name: Release XXName
          draft: false
          prerelease: true
