name: gmc build and release

on:
  push:
    branches: [master, develop, branches/cidi]
  pull_request:
    branches: [master, develop, branches/cidi]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.19.2"

      - name: Build & Test
        run: |
          echo Building ...
